replicaCount: 1

image:
  repository: paolodocker21/jenkinstest
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000
  nodePort: 31500

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
